using System.Text;

namespace GoLive.Saturn.Generator.Cascade;

public static class CascadeEmitter
{
    public static string Emit(CascadeClassMapping mapping)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Emitted by GoLive.Saturn.Generator.Cascade");
        sb.AppendLine("#nullable disable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(mapping.Namespace))
        {
            sb.Append("namespace ").Append(mapping.Namespace).AppendLine();
            sb.AppendLine("{");
        }

        sb.Append("public partial class ").AppendLine(mapping.ClassName);
        sb.AppendLine("{");

        foreach (var child in mapping.Children)
        {
            if (child.EmitOverride)
            {
                AppendOverride(sb, child);
            }
        }

        sb.AppendLine("    public static class __Cascade");
        sb.AppendLine("    {");
        sb.AppendLine("        public static global::GoLive.Saturn.Data.Entities.Cascade.CascadeRelationSnapshot[] For");
        sb.AppendLine("            => __CascadeSnapshot.Value;");
        sb.AppendLine();
        sb.AppendLine("        private static readonly global::System.Lazy<global::GoLive.Saturn.Data.Entities.Cascade.CascadeRelationSnapshot[]> __CascadeSnapshot =");
        sb.AppendLine("            new(() => new global::GoLive.Saturn.Data.Entities.Cascade.CascadeRelationSnapshot[]");
        sb.AppendLine("            {");

        for (int i = 0; i < mapping.Children.Count; i++)
        {
            var c = mapping.Children[i];
            sb.Append("                new global::GoLive.Saturn.Data.Entities.Cascade.CascadeRelationSnapshot(");
            sb.Append("typeof(").Append(c.ParentTypeFullName).Append("), ");
            sb.Append("typeof(").Append(c.ChildTypeFullName).Append("), ");
            sb.Append("global::GoLive.Saturn.Data.Entities.Cascade.CascadeMode.").Append(c.Mode).Append(", ");
            sb.Append("global::GoLive.Saturn.Data.Entities.Cascade.CascadeDepth.").Append(c.Depth).Append(", ");
            sb.Append("global::GoLive.Saturn.Data.Entities.Cascade.SharedScopePolicy.").Append(c.SharedScope).Append(")");
            sb.AppendLine(i == mapping.Children.Count - 1 ? string.Empty : ",");
        }

        sb.AppendLine("            });");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        if (!string.IsNullOrEmpty(mapping.Namespace))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static void AppendOverride(StringBuilder sb, CascadeChildMapping c)
    {
        var propName = c.PropertyName;
        var propType = c.PropertyTypeFullName;
        var basePropName = propName;

        sb.Append("    [global::GoLive.Saturn.Data.Entities.Cascade.CascadeDelete(");
        sb.Append("global::GoLive.Saturn.Data.Entities.Cascade.CascadeMode.").Append(c.Mode).Append(", ");
        sb.Append("global::GoLive.Saturn.Data.Entities.Cascade.CascadeDepth.").Append(c.Depth).Append(", ");
        sb.Append("global::GoLive.Saturn.Data.Entities.Cascade.SharedScopePolicy.").Append(c.SharedScope);
        sb.AppendLine(")]");
        sb.Append("    public override ").Append(propType).Append(' ').AppendLine(propName);
        sb.AppendLine("    {");
        sb.Append("        get => base.").AppendLine(basePropName + ";");
        sb.Append("        set => base.").Append(basePropName).AppendLine(" = value;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }
}
