# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.300'
- script: dotnet build GoLive.Saturn.Data/GoLive.Saturn.Data.csproj
- script: dotnet publish GoLive.Saturn.Data/GoLive.Saturn.Data.csproj --output $(Build.ArtifactStagingDirectory)
- script: dotnet pack GoLive.Saturn.Data/GoLive.Saturn.Data.csproj /p:PackageVersion=$(version) --output $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1