namespace Saturn.Generator.Entities.Tests;

public class StabilizationTests
{
    private const string Source = """
        using System.ComponentModel.DataAnnotations;
        using GoLive.Saturn.Data.Entities;
        using GoLive.Saturn.Generator.Entities.Resources;

        namespace Sample;

        public partial class Parent : Entity
        {
            [AddToLimitedView("View1")]
            public partial string? Name { get; set; }
        }

        public partial class Child : Entity
        {
            [Required]
            [AddToLimitedView("View1")]
            public partial string? Title { get; set; }

            private string code = string.Empty;

            private void code_runAfterSet(string incoming)
            {
            }

            [AddToLimitedView("View1")]
            private Ref<Parent> parent;
        }
        """;

    [Fact]
    public void Generated_File_Has_AutoGenerated_Header()
    {
        Assert.StartsWith("// <auto-generated/>", GeneratorTestHarness.GeneratedFor(Source, "Child.g.cs"));
    }

    [Fact]
    public void Generated_File_Has_GeneratedCode_Attribute()
    {
        Assert.Contains("GeneratedCode(\"Saturn.Generator.Entities\"", GeneratorTestHarness.GeneratedFor(Source, "Child.g.cs"));
    }

    [Fact]
    public void View_UpdateFrom_Is_Null_Guarded()
    {
        Assert.Contains("if (source is null)", GeneratorTestHarness.GeneratedFor(Source, "Child.g.cs"));
    }

    [Fact]
    public void Ref_Implicit_Operator_Is_Null_Safe()
    {
        var generated = GeneratorTestHarness.GeneratedFor(Source, "Child.g.cs");

        Assert.Contains("implicit operator Child_View1? (Ref<Child> source)", generated);
        Assert.Contains("if (source?.Item is null)", generated);
    }

    [Fact]
    public void String_RunAfterSet_Hook_Is_Invoked()
    {
        var generated = GeneratorTestHarness.GeneratedFor(Source, "Child.g.cs");
        Assert.Contains("code_runAfterSet(value);", generated);
    }

    [Fact]
    public void Property_Attribute_Is_Copied_To_View()
    {
        Assert.Contains("RequiredAttribute", GeneratorTestHarness.GeneratedFor(Source, "Child.g.cs"));
    }

    [Fact]
    public void Nullability_Is_Preserved_On_Generated_Property()
    {
        Assert.Contains("string? Title", GeneratorTestHarness.GeneratedFor(Source, "Child.g.cs"));
    }

    [Fact]
    public void Non_Entity_Partial_Class_Produces_No_Source()
    {
        const string source = """
            namespace Sample;

            public partial class NotAnEntity
            {
                private string name;
            }
            """;

        Assert.Empty(GeneratorTestHarness.Run(source));
    }
}
