using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace GoLive.Saturn.Generator.Entities;

public static class SourceCodeGenerator
{
    private const string GeneratedCodeAttribute = "[global::System.CodeDom.Compiler.GeneratedCode(\"Saturn.Generator.Entities\", \"1.0.0\")]";

    public static void Generate(SourceStringBuilder source, ClassToGenerate classToGen)
    {
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable annotations");
        source.AppendLine("#nullable disable warnings");
        source.AppendLine("using System;");
        source.AppendLine("using System.ComponentModel;");
        source.AppendLine("using System.Runtime.CompilerServices;");
        source.AppendLine("using System.Linq.Expressions;");
        source.AppendLine("using GoLive.Saturn.Generator.Entities.Resources;");
        source.AppendLine("using GoLive.Saturn.Data.Entities;");
        source.AppendLine("using System.Collections.Specialized;");
        source.AppendLine("using System.Collections.Generic;");
        /*source.AppendLine("using FastMember;");*/
        source.AppendLine("using System.Linq;");

        source.AppendLine($"namespace {classToGen.Namespace};");

        source.AppendLine(GeneratedCodeAttribute);
        source.AppendLine($"public partial class {classToGen.Name} : INotifyPropertyChanged");

        if (classToGen.TrackChanges)
        {
            source.AppendLine(", global::GoLive.Saturn.Data.ChangeTracking.ITrackable");
            source.AppendLine(", global::GoLive.Saturn.Data.ChangeTracking.ITrackableMetadata");
        }

        var updatableFromChildren = classToGen.Members.SelectMany(e => e.LimitedViews.Where(f => f.TwoWay).Select(f => f.Name)).Distinct().ToList();

        if (updatableFromChildren.Any())
        {
            foreach (var s in updatableFromChildren)
            {
                source.AppendLine($", IUpdatableFrom<{classToGen.Name}_{s}>");
                source.AppendLine($", ICreatableFrom<{classToGen.Name}_{s}>");
            }
        }

        source.AppendLine("{");
        source.AppendIndent();

        foreach (var memberToGenerate in classToGen.Members.Where(e => e.IsPartialProperty))
        {
            source.AppendLine($"private {RenderType(memberToGenerate.Type)} {memberToGenerate.Name};");
        }

        if (classToGen.Members.Any(f => f.IsCollection) || classToGen.HasInitMethod)
        {
            source.AppendLine($"public {classToGen.Name}()");
            source.AppendOpenCurlyBracketLine();

            if (classToGen.HasInitMethod)
            {
                source.AppendLine("_init();");
            }

            foreach (var coll in classToGen.Members.Where(f => f.IsCollection))
            {
                var collTargetName = coll.Name.FirstCharToUpper();
                source.AppendLine($"{collTargetName} = new();");

                if (coll.DoNotTrackChanges)
                {
                    continue;
                }

                var keySuffix = CollectionItemKeySuffix(coll.CollectionType);

                source.AppendLine($"{collTargetName}.CollectionChanged += (in ObservableCollections.NotifyCollectionChangedEventArgs<{coll.CollectionType.ToDisplayString()}> eventArgs) =>");
                source.AppendOpenCurlyBracketLine();
                source.AppendLine("if (!EnableChangeTracking || Changes == null) return;");
                source.AppendLine("switch (eventArgs.Action)");
                source.AppendOpenCurlyBracketLine();

                source.AppendLine("case System.Collections.Specialized.NotifyCollectionChangedAction.Add:");
                source.AppendLine($"Changes[$\"{collTargetName}.{{eventArgs.NewItem{keySuffix}}}\"] = eventArgs.NewItem;");
                source.AppendLine("break;");

                source.AppendLine("case System.Collections.Specialized.NotifyCollectionChangedAction.Remove:");
                source.AppendLine($"Changes.Remove($\"{collTargetName}.{{eventArgs.OldItem{keySuffix}}}\");");
                source.AppendLine("break;");

                source.AppendLine("case System.Collections.Specialized.NotifyCollectionChangedAction.Replace:");
                source.AppendLine($"Changes.Remove($\"{collTargetName}.{{eventArgs.OldItem{keySuffix}}}\");");
                source.AppendLine($"Changes[$\"{collTargetName}.{{eventArgs.NewItem{keySuffix}}}\"] = eventArgs.NewItem;");
                source.AppendLine("break;");

                source.AppendLine("case System.Collections.Specialized.NotifyCollectionChangedAction.Move:");
                source.AppendLine("break;");

                source.AppendLine("case System.Collections.Specialized.NotifyCollectionChangedAction.Reset:");
                source.AppendLine($"foreach (var key in Changes.Keys.Where(k => k.StartsWith(\"{collTargetName}.\")).ToList())");
                source.AppendOpenCurlyBracketLine();
                source.AppendLine("Changes.Remove(key);");
                source.AppendCloseCurlyBracketLine();
                source.AppendLine("break;");

                source.AppendCloseCurlyBracketLine();
                source.AppendCloseCurlyBracketLine();
                source.AppendLine(";");
            }

            source.AppendCloseCurlyBracketLine();
        }

        foreach (var member in classToGen.Members.Where(f => !f.UseOnlyForLimited))
        {
            if (member.IsCollection)
            {
                GenerateCollectionMember(source, member);
            }
            else
            {
                GenerateNormalMember(source, member, classToGen);
            }
        }


        if (updatableFromChildren.Any())
        {
            foreach (var s in updatableFromChildren)
            {
                source.AppendLine($"public void UpdateFrom({classToGen.Name}_{s} input) => input.UpdateParent(this);");
                source.AppendLine($"public static ICreatableFrom<{classToGen.Name}_{s}> Create({classToGen.Name}_{s} input )");
                source.AppendOpenCurlyBracketLine();
                source.AppendLine($"var item = new {classToGen.Name}();");
                source.AppendLine("item.UpdateFrom(input);");
                source.AppendLine("");
                source.AppendLine("if (input is IUniquelyIdentifiable inputWithId)");
                source.AppendOpenCurlyBracketLine();
                source.AppendLine("item.Id = inputWithId.Id;");
                source.AppendCloseCurlyBracketLine();
                source.AppendLine("return item;");
                source.AppendCloseCurlyBracketLine();
            }
        }

        foreach (var item in classToGen.Members.Where(r => r.LimitedViews.Any()).SelectMany(f => f.LimitedViews.Select(r => new { classDef = f, LimitedView = r }))
                     .GroupBy(e => e.LimitedView.Name))
        {
            source.AppendLine($"public {classToGen.Name}_{item.Key} To_{item.Key}() => {classToGen.Name}_{item.Key}.Generate(this);");
        }

        // Feature 1: emit To_ViewName() for views that exist only on the parent (no child members added)
        foreach (var viewName in classToGen.ParentOnlyViewNames)
        {
            source.AppendLine($"public {classToGen.ParentClassName}_{viewName} To_{viewName}() => {classToGen.ParentClassName}_{viewName}.Generate(this);");
        }

        if (classToGen.TrackChanges)
        {
            TrackingGenerator.EmitEntityTracking(source, classToGen);
        }

        source.AppendLine("}");

        source.DecreaseIndent();
        source.AppendLine(2);


        foreach (var item in classToGen.Members.Where(r => r.LimitedViews.Any())
                     .SelectMany(f => f.LimitedViews.Select(r => new { classDef = f, LimitedView = r }))
                     .GroupBy(e => e.LimitedView.Name))
        {
            source.AppendLine(GeneratedCodeAttribute);

            if (classToGen.InheritsParentLimitedViews && !classToGen.FlattenParentLimitedViews && !string.IsNullOrWhiteSpace(classToGen.ParentClassName))
            {
                // Inherit from parent view class; parent already implements IUpdatableFrom<ParentClass>/ICreatableFrom<ParentClass>
                source.AppendLine($"public partial class {classToGen.Name}_{item.Key} : {classToGen.ParentClassName}_{item.Key}, IUpdatableFrom<{classToGen.Name}>, ICreatableFrom<{classToGen.Name}>");
            }
            else
            {
                source.AppendLine($"public partial class {classToGen.Name}_{item.Key} : IUpdatableFrom<{classToGen.Name}>, ICreatableFrom<{classToGen.Name}>");
            }

            if (item.Any(e => e.LimitedView.TwoWay))
            {
                source.AppendLine($", IUpdatableFrom<{classToGen.Name}_{item.Key}>");
            }

            // Emit IUniquelyIdentifiable for non-inherit, or flatten (both are flat view classes)
            if ((!classToGen.InheritsParentLimitedViews || classToGen.FlattenParentLimitedViews) && classToGen.ParentItemToGenerate is { Count: > 0 } && (classToGen.ParentItemToGenerate.Any(r => r.ViewName == item.Key) || classToGen.ParentItemToGenerate.Any(r => r.ViewName == "*")))
            {
                var addedUniquelyIdentifiable = false;

                foreach (var toGenerate in classToGen.ParentItemToGenerate.Where(r => r.ViewName == item.Key && r.InheritFromIUniquelyIdentifiable))
                {
                    source.AppendLine(", IUniquelyIdentifiable");
                    addedUniquelyIdentifiable = true;

                    break;
                }

                if (!addedUniquelyIdentifiable)
                {
                    foreach (var toGenerate in classToGen.ParentItemToGenerate.Where(r => r.ViewName == "*" && r.InheritFromIUniquelyIdentifiable))
                    {
                        source.AppendLine(", IUniquelyIdentifiable");
                        addedUniquelyIdentifiable = true;

                        break;
                    }
                }
            }

            source.AppendOpenCurlyBracketLine();

            source.AppendLine($"public static implicit operator {classToGen.Name}_{item.Key} ({classToGen.Name} source)");
            source.AppendOpenCurlyBracketLine();
            source.AppendLine($"var retr = new {classToGen.Name}_{item.Key}();");
            source.AppendLine("retr.UpdateFrom(source);");
            source.AppendLine("return retr;");
            source.AppendCloseCurlyBracketLine();


            source.AppendLine($"public static implicit operator {classToGen.Name}_{item.Key}? (Ref<{classToGen.Name}> source)");
            source.AppendOpenCurlyBracketLine();
            source.AppendLine("if (source?.Item is null)");
            source.AppendOpenCurlyBracketLine();
            source.AppendLine("return null;");
            source.AppendCloseCurlyBracketLine();
            source.AppendLine($"var retr = new {classToGen.Name}_{item.Key}();");
            source.AppendLine("retr.UpdateFrom(source.Item);");
            source.AppendLine("return retr;");
            source.AppendCloseCurlyBracketLine();


            foreach (var v1 in item)
            {
                var classDef = v1.classDef;
                outputAttributes(source, classDef);

                var initString = string.IsNullOrWhiteSpace(v1.LimitedView.Initializer) ? string.Empty : $" = {v1.LimitedView.Initializer};";
                var accessors = v1.LimitedView.ReadOnly ? "{get;}" : "{get;set;}";

                if (string.IsNullOrWhiteSpace(v1.LimitedView.OverrideReturnTypeToUseLimitedView))
                {
                    source.AppendLine($"public {RenderType(classDef.Type)} {classDef.Name.FirstCharToUpper()} {accessors} {initString}");
                }
                else
                {
                    source.AppendLine($"public {v1.LimitedView.OverrideReturnTypeToUseLimitedView} {classDef.Name.FirstCharToUpper()} {accessors} {initString}");
                }
            }

            if ((!classToGen.InheritsParentLimitedViews || classToGen.FlattenParentLimitedViews) && classToGen.ParentItemToGenerate is { Count: > 0 } && (classToGen.ParentItemToGenerate.Any(r => r.ViewName == item.Key) || classToGen.ParentItemToGenerate.Any(r => r.ViewName == "*")))
            {
                source.AppendLine(2);

                foreach (var toGenerate in classToGen.ParentItemToGenerate.Where(r => r.ViewName == item.Key))
                {
                    source.AppendLine($"public {getLimitedViewName(toGenerate.Property.Type, toGenerate.OverrideReturnTypeToUseLimitedView)} {toGenerate.ChildPropertyName} {{get;set;}}");
                }

                foreach (var toGenerate in classToGen.ParentItemToGenerate.Where(r => r.ViewName == "*"))
                {
                    source.AppendLine($"public {getLimitedViewName(toGenerate.Property.Type, toGenerate.OverrideReturnTypeToUseLimitedView)} {toGenerate.ChildPropertyName} {{get;set;}}");
                }
            }

            source.AppendLine(2);

            outputViewUpdateFromMethod(source, classToGen, item.Key, item.Select(r => (r.classDef, r.LimitedView)));
            outputViewUpdateFromSelfMethod(source, classToGen, item.Key, item.Select(r => (r.classDef, r.LimitedView)));
            outputViewGenerateMethod(source, classToGen, item.Key);
            outputViewSelector(source, classToGen, item.Key, item.Select(r => (r.classDef, r.LimitedView)));

            outputViewTwoWayMethod(source, classToGen, item.Key, item.Select(r => (r.classDef, r.LimitedView)));

            source.AppendLine($"public static ICreatableFrom<{classToGen.Name}> Create({classToGen.Name} input) => Generate(input);");

            source.AppendCloseCurlyBracketLine();
        }

        if (classToGen.GenerateDto && !classToGen.DtoAlreadyExists)
        {
            DtoGenerator.Generate(source, classToGen, classToGen.DtoExpandRefs, classToGen.DtoUseFullId, classToGen.Namespace, classToGen.DtoTrackChanges);
        }
    }

    private static string getLimitedViewName(ITypeSymbol input, string limitedView)
    {
        if (string.IsNullOrWhiteSpace(limitedView))
        {
            return input.ToDisplayString();
        }

        return limitedView;
    }

    private static string BuildComputedValueExpression((MemberToGenerate classDef, LimitedViewToGenerate LimitedView) v1, bool selectorContext)
    {
        var valueExpression = $"source.{v1.classDef.Name.FirstCharToUpper()}";

        if (selectorContext && !string.IsNullOrWhiteSpace(v1.LimitedView.ComputedSelectorExpression))
        {
            return v1.LimitedView.ComputedSelectorExpression.Replace("{value}", valueExpression);
        }

        if (!string.IsNullOrWhiteSpace(v1.LimitedView.ComputedExpression))
        {
            return v1.LimitedView.ComputedExpression.Replace("{value}", valueExpression);
        }

        if (v1.LimitedView.ComputedProperty != null)
        {
            var dotAccess = $"{valueExpression}.{v1.LimitedView.ComputedProperty}";
            if (v1.LimitedView.DisableComputedPropertyDefault)
            {
                return dotAccess;
            }
            return selectorContext ? $"{valueExpression} != null ? {dotAccess} : default" : $"{valueExpression}?.{v1.LimitedView.ComputedProperty} ?? default";
        }

        return valueExpression;
    }

    private static void outputViewTwoWayMethod(SourceStringBuilder source, ClassToGenerate classToGen, string itemKey, IEnumerable<(MemberToGenerate classDef, LimitedViewToGenerate LimitedView)> item)
    {
        if (item.Any(e => e.LimitedView.TwoWay))
        {
            source.AppendLine($"public void UpdateParent({classToGen.Name} parent)");
            source.AppendOpenCurlyBracketLine();

            foreach (var v1 in item)
            {
                if (string.IsNullOrWhiteSpace(v1.LimitedView.OverrideReturnTypeToUseLimitedView))
                {
                    source.AppendLine($"parent.{v1.classDef.Name.FirstCharToUpper()} = this.{v1.classDef.Name.FirstCharToUpper()};");
                }
                else
                {
                    source.AppendLine($"parent.{v1.classDef.Name.FirstCharToUpper()} =  this.{v1.classDef.Name.FirstCharToUpper()}.Id;");
                    // TODO need to do this at one point, maybe with some interfaces
                }
            }

            source.AppendCloseCurlyBracketLine();
        }
    }

    private static void outputViewUpdateFromSelfMethod(SourceStringBuilder source, ClassToGenerate classToGen, string itemKey, IEnumerable<(MemberToGenerate classDef, LimitedViewToGenerate LimitedView)> item)
    {
        if (item.Any(e => e.LimitedView.TwoWay))
        {
            source.AppendLine($"public void UpdateFrom({classToGen.Name}_{itemKey} self)");
            source.AppendOpenCurlyBracketLine();

            foreach (var v1 in item)
            {
                source.AppendLine($"this.{v1.classDef.Name.FirstCharToUpper()} = self.{v1.classDef.Name.FirstCharToUpper()};");
            }

            source.AppendCloseCurlyBracketLine();
        }
    }

    private static void outputViewUpdateFromMethod(SourceStringBuilder source, ClassToGenerate classToGen, string itemKey, IEnumerable<(MemberToGenerate classDef, LimitedViewToGenerate LimitedView)> item)
    {
        source.AppendLine($"protected virtual void OnUpdateFromStart({classToGen.Name} source) {{ }}");
        source.AppendLine($"protected virtual void OnUpdateFromEnd({classToGen.Name} source) {{ }}");
        source.AppendLine($"public void UpdateFrom({classToGen.Name} source)");
        source.AppendOpenCurlyBracketLine();
        source.AppendLine("if (source is null)");
        source.AppendOpenCurlyBracketLine();
        source.AppendLine("return;");
        source.AppendCloseCurlyBracketLine();
        source.AppendLine("OnUpdateFromStart(source);");

        if (classToGen.InheritsParentLimitedViews && !classToGen.FlattenParentLimitedViews && !string.IsNullOrWhiteSpace(classToGen.ParentClassName))
        {
            // Call the parent view's UpdateFrom, casting to parent type
            source.AppendLine($"base.UpdateFrom(({classToGen.ParentClassName})source);");
        }

        foreach (var v1 in item)
        {
            source.AppendLine($"this.{v1.classDef.Name.FirstCharToUpper()} = {BuildComputedValueExpression(v1, false)};");
        }

        if ((!classToGen.InheritsParentLimitedViews || classToGen.FlattenParentLimitedViews) && classToGen.ParentItemToGenerate is { Count: > 0 } && (classToGen.ParentItemToGenerate.Any(r => r.ViewName == itemKey) || classToGen.ParentItemToGenerate.Any(r => r.ViewName == "*")))
        {
            source.AppendLine(2);

            foreach (var toGenerate in classToGen.ParentItemToGenerate.Where(r => r.ViewName == itemKey))
            {
                source.AppendLine($"this.{toGenerate.ChildPropertyName} = source.{toGenerate.PropertyName};");
            }

            foreach (var toGenerate in classToGen.ParentItemToGenerate.Where(r => r.ViewName == "*"))
            {
                source.AppendLine($"this.{toGenerate.ChildPropertyName} = source.{toGenerate.PropertyName};");
            }
        }

        source.AppendLine("OnUpdateFromEnd(source);");
        source.AppendLine();
        source.AppendCloseCurlyBracketLine();
    }

    private static void outputViewGenerateMethod(SourceStringBuilder source, ClassToGenerate classToGen, string itemKey)
    {
        source.AppendLine($"protected virtual void OnGenerateStart({classToGen.Name} source, {classToGen.Name}_{itemKey} result) {{ }}");
        source.AppendLine($"protected virtual void OnGenerateEnd({classToGen.Name} source, {classToGen.Name}_{itemKey} result) {{ }}");
        var newKeyword = (classToGen.InheritsParentLimitedViews && !classToGen.FlattenParentLimitedViews) ? "new " : string.Empty;
        source.AppendLine($"public static {newKeyword}{classToGen.Name}_{itemKey} Generate({classToGen.Name} source)");
        source.AppendOpenCurlyBracketLine();
        source.AppendLine($"var retr = new {classToGen.Name.FirstCharToUpper()}_{itemKey}();");
        source.AppendLine("retr.OnGenerateStart(source, retr);");
        source.AppendLine("retr.UpdateFrom(source);");
        source.AppendLine("retr.OnGenerateEnd(source, retr);");
        source.AppendLine("return retr;");
        source.AppendCloseCurlyBracketLine();
    }

    private static void outputViewSelector(SourceStringBuilder source, ClassToGenerate classToGen, string itemKey,
        IEnumerable<(MemberToGenerate classDef, LimitedViewToGenerate LimitedView)> item)
    {
        source.AppendLine($"public static Expression<Func<{classToGen.Name}, {classToGen.Name}_{itemKey}>> Selector => source => new {classToGen.Name}_{itemKey}");
        source.AppendOpenCurlyBracketLine();

        foreach (var v1 in item)
        {
            source.AppendLine($"{v1.classDef.Name.FirstCharToUpper()} = {BuildComputedValueExpression(v1, true)},");
        }

        if ((!classToGen.InheritsParentLimitedViews || classToGen.FlattenParentLimitedViews)
            && classToGen.ParentItemToGenerate is { Count: > 0 }
            && (classToGen.ParentItemToGenerate.Any(r => r.ViewName == itemKey) || classToGen.ParentItemToGenerate.Any(r => r.ViewName == "*")))
        {
            foreach (var toGenerate in classToGen.ParentItemToGenerate.Where(r => r.ViewName == itemKey))
            {
                source.AppendLine($"{toGenerate.ChildPropertyName} = source.{toGenerate.PropertyName},");
            }

            foreach (var toGenerate in classToGen.ParentItemToGenerate.Where(r => r.ViewName == "*"))
            {
                source.AppendLine($"{toGenerate.ChildPropertyName} = source.{toGenerate.PropertyName},");
            }
        }

        source.AppendCloseCurlyBracketLine();
        source.AppendLine(";");
    }

    private static void outputAttributes(SourceStringBuilder source, MemberToGenerate classDef)
    {
        if (classDef.AdditionalAttributes.Count <= 0)
        {
            return;
        }

        foreach (var attr in classDef.AdditionalAttributes)
        {
            var parameters = new List<string>();
            parameters.AddRange(attr.ConstructorParameters);
            parameters.AddRange(attr.NamedParameters.Select(p => $"{p.Key}={p.Value}"));

            source.AppendLine($"[{attr.Name}({string.Join(",", parameters)})]");
        }
    }

    internal static string RenderType(ITypeSymbol type)
    {
        if (type is null)
        {
            return "object";
        }

        var text = type.ToDisplayString();

        if (type.IsReferenceType && type.NullableAnnotation == NullableAnnotation.Annotated && !text.EndsWith("?", StringComparison.Ordinal))
        {
            text += "?";
        }

        return text;
    }

    private static string StringHookArgument(MemberToGenerate item)
        => item.Type is not null && item.Type.OriginalDefinition.ToString() == "GoLive.Saturn.Data.Entities.Ref<T>" ? "value.Id" : "value";

    private static string CollectionItemKeySuffix(ITypeSymbol elementType)
    {
        if (elementType == null)
        {
            return string.Empty;
        }

        if (elementType is INamedTypeSymbol { TypeArguments.Length: 1 } named
            && named.OriginalDefinition.ToString() == "GoLive.Saturn.Data.Entities.Ref<T>")
        {
            return "?.Id";
        }

        if (elementType.GetMembers("Id").OfType<IPropertySymbol>().Any(p => p.GetMethod != null && p.DeclaredAccessibility != Accessibility.Private))
        {
            return "?.Id";
        }

        return elementType.AllInterfaces.Any(i => i.ToString() == "GoLive.Saturn.Data.Entities.IUniquelyIdentifiable") ? "?.Id" : string.Empty;
    }

    private static string NoTrackingSetterBody(MemberToGenerate item, string valueExpression)
    {
        return $@"if (EqualityComparer<{item.Type.ToDisplayString()}>.Default.Equals({item.Name}, {valueExpression})) return;
{item.Name} = {valueExpression};
OnPropertyChanged(nameof({item.Name.FirstCharToUpper()}));";
    }

    private static string ScopedSetValue(MemberToGenerate item, string valueExpression)
    {
        if (!item.DoNotTrackChanges)
        {
            return $"SetField(ref this.{item.Name}, {valueExpression});";
        }

        return $@"var valueToSet = {valueExpression};
if (EqualityComparer<{item.Type.ToDisplayString()}>.Default.Equals({item.Name}, valueToSet)) return;
{item.Name} = valueToSet;
OnPropertyChanged(nameof({item.Name.FirstCharToUpper()}));";
    }

    private static string ScopedClearValue(MemberToGenerate item)
    {
        if (!item.DoNotTrackChanges)
        {
            return $"SetField(ref this.{item.Name}, null);";
        }

        return $@"if (EqualityComparer<{item.Type.ToDisplayString()}>.Default.Equals({item.Name}, null)) return;
{item.Name} = null;
OnPropertyChanged(nameof({item.Name.FirstCharToUpper()}));";
    }

    private static void GenerateCollectionMember(SourceStringBuilder source, MemberToGenerate item)
    {
        var itemName = item.Name;
        source.AppendLine($"public {(item.IsPartialProperty ? "partial" : string.Empty)} ObservableCollections.ObservableList<{RenderType(item.CollectionType!)}> {itemName.FirstCharToUpper()}");
        source.AppendOpenCurlyBracketLine();
        source.AppendLine($"get => {itemName};");

        if (item.DoNotTrackChanges)
        {
            source.AppendLine("set");
            source.AppendOpenCurlyBracketLine();
            source.AppendLine(NoTrackingSetterBody(item, "value"));
            source.AppendCloseCurlyBracketLine();
        }
        else
        {
            source.AppendLine($"set => SetField(ref this.{itemName}, value);");
        }

        source.AppendCloseCurlyBracketLine();
    }

    private static void GenerateNormalMember(SourceStringBuilder source, MemberToGenerate item, ClassToGenerate classToGen)
    {
        var itemName = item.Name;

        if (!string.IsNullOrEmpty(item.XmlDocumentation))
        {
            source.AppendLine(item.XmlDocumentation);
            source.AppendLine();
        }

        if (!item.IsPartialProperty)
        {
            outputAttributes(source, item);
        }

        source.AppendLine($"public {(item.IsPartialProperty ? "partial" : string.Empty)} {RenderType(item.Type)} {itemName.FirstCharToUpper()}");
        source.AppendOpenCurlyBracketLine();

        if (!item.WriteOnly)
        {
            source.AppendLine($"get => {itemName};");
        }

        if (item.IsScoped
            && classToGen.IsMultiscopedEntity
            && item.Type is { } scopedType
            && scopedType.OriginalDefinition.ToString() == "GoLive.Saturn.Data.Entities.Ref<T>")
        {
            var setValue = ScopedSetValue(item, $"value.Item ?? new {item.Type.ToDisplayString()}(value.Id)");
            var clearValue = ScopedClearValue(item);
            var simpleValue = getSimpleValue(item);

            source.AppendLine($@"set
        {{
            if (value != null)
            {{
                if (string.IsNullOrWhiteSpace(value.Id))
                {{
                    Scopes.RemoveAll(f => f == {itemName}?.Id);
                    {clearValue}
                }}
                else
                {{
                    if (!Scopes.Contains(value.Id))
                    {{
                        Scopes.Add(value.Id);
                    }}
                    {setValue}
                    {simpleValue}
                }}
            }}
            else
            {{
                if ({itemName} != null && !string.IsNullOrWhiteSpace({itemName}.Id))
                {{
                    Scopes.RemoveAll(f => f == {itemName}.Id);
                }}
                {clearValue}
            }}
        }}");
        }
        else if (!item.ReadOnly)
        {
            var hasRunAfterSetHook = item.HasRunAfterSetMethodSimple || item.HasRunAfterSetMethodIsString;
            var runAfterSetArgument = item.HasRunAfterSetMethodIsString ? StringHookArgument(item) : "value";

            if (item.DoNotTrackChanges)
            {
                source.AppendLine("set");
                source.AppendOpenCurlyBracketLine();
                source.AppendLine(NoTrackingSetterBody(item, "value"));

                if (hasRunAfterSetHook)
                {
                    source.AppendLine($"{itemName}_runAfterSet({runAfterSetArgument});");
                }

                source.AppendCloseCurlyBracketLine();
            }
            else if (hasRunAfterSetHook)
            {
                source.Append($@"set
        {{
            SetField(ref this.{itemName}, value);
            {itemName}_runAfterSet({runAfterSetArgument});
        }}");
            }
            else
            {
                source.AppendLine($"set => SetField(ref this.{itemName}, value);");
            }
        }

        source.AppendCloseCurlyBracketLine();

        if (item.HasRunAfterSetMethodIsRefItem && !string.IsNullOrWhiteSpace(item.RefType))
        {
            source.AppendLine($"[System.ComponentModel.EditorBrowsable(EditorBrowsableState.Never)] public static Func<string, {item.RefType}> _{itemName}_runAfterSet_fetch;");
            source.AppendLine("");
        }

        string getSimpleValue(MemberToGenerate item)
        {
            if (item.HasRunAfterSetMethodSimple || item.HasRunAfterSetMethodIsRefItem)
            {
                return $@"{item.Name}_runAfterSet(value);";
            }

            return item.HasRunAfterSetMethodIsString ? $@"{item.Name}_runAfterSet(value.Id);" : string.Empty;
        }
    }
}